server:
  port: 8084
eureka:
  instance:
  hostname: localhost
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path= /user/**
        - id: contact-service
          uri: lb://contact-service
          predicates:
            - Path= /contact/**

